### ISSUE TITLE
Perhaps paper is not supported?

### ISSUE THREAD

**Issue by ttt31** [Andavin/Images#1]
I tried to delete the installed image but cannot. No right click ...
Perhaps paper is not supported?

**Comment by Andavin** [comment]
Paper is supported. Do you get any errors in console when you attempt this? What version of the server are you on? You may also want to try to use ProtocolLib if you have a lot of issues.

**Comment by Andavin** [comment]
I'm closing this issue since I haven't got a response and as far as I know Paper should be fully supported by this project.
