### ISSUE TITLE
Could not find artifact

### ISSUE THREAD

**Issue by TheZitroX** [Andavin/Images#102]
Could not find artifact org.spigotmc:spigot:jar:remapped-mojang:1.21-R0.1-SNAPSHOT in spigotmc-repo (https://hub.spigotmc.org/nexus/content/groups/public/)

**### Am I doing shit wrong or what exactly**? Shouldn't maven be compiled and go?

**Comment by TheZitroX** [comment]
It compiles now after f* around for 6h and changed the version 1.21{…} to 1.21.1-R0.1-SNAPSHOT

**Comment by resi23** [comment]
*close*
