### ISSUE TITLE
1.16.1 Plugin not working

### ISSUE THREAD

**Issue by chipamogli00** [Andavin/Images#11]
The plugin is not working, it does not even let me put the / image command, it does not recognize it.
The plugin is very good, I like it a lot and in the theme of my server it is essential, I hope there will be a solution soon.

**Comment by chipamogli00** [comment]
Before yesterday I had my server in version 1.15.2 and the plugin worked perfectly, I had it updated to the latest version, and when I updated the server it stopped working ...

**Comment by Andavin** [comment]
I'm assuming this is fixed. Let me know, if not and I'll reopen it
