### ISSUE TITLE
Does not support 1.20.6 paper

### ISSUE THREAD

**Issue by masood151117** [Andavin/Images#114]
if you can , please fix this

**Comment by masood151117** [comment]
all my gamemodes are 1.20.6
and i tested versions from 2.3 to 2.5.3

**Comment by masood151117** [comment]
@resi23 can you send 2.3.3

**Comment by masood151117** [comment]
or any fixed paper build

**Comment by resi23** [comment]
Spamming doesn't make it any faster.
you look on plugin page [https://www.spigotmc.org/threads/custom-images.302109/page-37#post-4807214 for](https://www.spigotmc.org/resources/custom-images.53036/) for me works on paper

**Comment by masood151117** [comment]
> Spamming doesn't make it any faster. It just annoys me and I don't do anything about it. you look on plugin page [https://www.spigotmc.org/threads/custom-images.302109/page-37#post-4807214 for](https://www.spigotmc.org/resources/custom-images.53036/) for me works on paper

test it on 1.20.6 not 1.21

**Comment by Andavin** [comment]
Check out this other issue: https://github.com/Andavin/Images/issues/109#issuecomment-2546647705

Please comment there if you still have issues.
