### ISSUE TITLE
Cannot delete images after they are placed

### ISSUE THREAD

**Issue by jackgraddon** [Andavin/Images#12]

**Comment by jackgraddon** [comment]
I accidentally submitted without adding any comments
![image](https://user-images.githubusercontent.com/61634132/92664723-9ae82c80-f2b9-11ea-8d21-32403b1bf5b1.png)
 we placed this file, but neither of us can get it to delete.
We use !image delete and right click on it, but it just stays.

**Comment by Andavin** [comment]
I hope you got this figured out. I was never able to reproduce this despite it happening to many people randomly.
