### ISSUE TITLE
Support for .webp images

### ISSUE THREAD

**Issue by JotaOdiceu** [Andavin/Images#15]
The webp image format is much lighter and does not lose quality compared to png, I believe that if the plugin were compatible with this format, imagesn would load faster, in addition to being lighter, hugs from Brazil, thanks.

**Comment by Andavin** [comment]
At the moment the plugin supports all images that Java BufferedImage supports. I'm actually unsure of the limit. You can try using the webp image format it may work.

**Comment by JotaOdiceu** [comment]
When trying to use the webp image format it either gives an error or says
unsupported format

Em sex., 4 de dez. de 2020 às 04:06, Mark Vogel <notifications@github.com>
escreveu:
