### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by LucidAPs** [Andavin/Images#19]
![image](https://user-images.githubusercontent.com/42933023/112430337-a88d6d00-8d46-11eb-8cd6-44f97ba2b937.png)
![image](https://user-images.githubusercontent.com/42933023/112430342-ab885d80-8d46-11eb-9be0-d1240839403c.png)
![image](https://user-images.githubusercontent.com/42933023/112430350-b0e5a800-8d46-11eb-917b-e6871dec247c.png)

**Comment by Andavin** [comment]
This is very interesting. Most likely all the image byte data, but I'll have to keep it in mind with the rewrite. Thanks for the info I appreciate it!
