### ISSUE TITLE
Add Reload Support?

### ISSUE THREAD

**Issue by jeffry1829** [Andavin/Images#2]
When I do /plugman unload Images, and then load back, the image i just create is no longer removable, I just can't break the image(even with /image delete ...).
And I thought there's no onDisable()? Async threads are not cancel when I unload the plugin?

**Comment by Andavin** [comment]
Yeah pretty much no effort is given to cleaning up spawned images on disabling of the plugin. Images were most likely replaced or duplicated while the entities themselves were either duplicated or the IDs messed up and no longer correspond to the image.

In any case, I will consider adding this, but anyone is also free to add a pull request.

**Comment by pquerner** [comment]
Do you mean by reload support to reload images from disk and redraw ?

**Comment by Andavin** [comment]
What I mean by reload support is fully reloading the plugin by disabling it and re-enabling cleaning up all objects in the process. For example, removing all images and reloading them from the database on re-enable etc.

**Comment by pquerner** [comment]
So closing this issue means its not wanted?
