### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by pquerner** [Andavin/Images#3]
I am trying to build this project but I get errors:

https://github.com/pquerner/Images/commit/2d7d50bfc4929209bd8928e3982fad52e65d3836

Is this something on my end?
I deleted the other modules because I got the same errors for different API versions, therefore I only left 1.15 since thats the version I play on.

**Comment by Andavin** [comment]
This uses Maven to build. If you set the project up correctly then it should build using something like `clean package`.
If  there is a problem, then it is most likely on your end yes. Your workspace must be setup correctly for a multi-module Maven build.

By the way, I have heard that Eclipse has trouble with mutli-module projects. If you are using that, then it could be the problem as I use IntelliJ IDEA.

**Comment by pquerner** [comment]
I am unable to access the repos somehow. I am using intellij and "clean package" as suggested.
