### ISSUE TITLE
Version for 1.18

### ISSUE THREAD

**Issue by sphings79** [Andavin/Images#31]
Hi,

would be really nice to have your plugin working on 1.18 server :)

regards

sphings

**Comment by cross** [comment]
FYI. It looks like there's a PR (#30 ) that should add this.  Hopefully @Andavin will be able to merge it soon.

**Comment by KeyboardKobold** [comment]
Yup! It's running fine with the PR #30 on our Spigot 1.18 Server. You can build it yourself by pulling the code from that fork.

**Comment by Andavin** [comment]
This ending up being resolved :)
