### ISSUE TITLE
Images replaces current maps locked

### ISSUE THREAD

**Issue by xEllesi** [Andavin/Images#33]
SO, my players like to mape huge maps on their lands to see their progress.
For some reason the images plugin bypass that locked maps and replaces it.. its possible to disable?

here's a print
![2022-01-06_19 02 59](https://user-images.githubusercontent.com/50302886/148436950-3f7a2fd9-8bd3-49a0-b710-5d8700d1db6a.png)

its supposed to be like that
![2022-01-06_19 01 36](https://user-images.githubusercontent.com/50302886/148436770-a9157391-0038-45ca-803b-83cb02433fef.png)

**Comment by Andavin** [comment]
This looks like it's do to an overflow of integer IDs on the maps themselves. It should be fixed with versions 1.13+ now. Let me know if it still is going on and I'll reopen this

**Comment by CloudeLecaw** [comment]
we also saw this issue 1-2 versions before.
well our solution was simplyreplaceing the "wrong" images with new once :3
