### ISSUE TITLE
Images exception generation

### ISSUE THREAD

**Issue by borjxrroyo** [Andavin/Images#34]
Hi there,

Although the plugin is working properly, sometimes we see that error in the console:

![image](https://user-images.githubusercontent.com/72812865/150139537-0c2626c7-6f20-42ce-9c9c-f7b829142ae2.png)

Thanks,
Borja

**Comment by Andavin** [comment]
I believe this was an issue with the 1.18 PR before it was accepted. If this is still going on let me know and I'll reopen this
