### ISSUE TITLE
Images doesnt instantly load on servers

### ISSUE THREAD

**Issue by Anldernx** [Andavin/Images#44]
My friend placed an image on our server but i had to relog onto the server to see it, is it posible that it loads for other players instantly/without reloging?

**Comment by CloudeLecaw** [comment]
On our server it got placed instandly. Why ever your server doesnt update it, its not the normal behave.
What server are you using? Might be a Client thing? Well there is nothing Images can do here.

**Comment by Andavin** [comment]
This definitely an odd issue, but I can't really say it will be fixed without a 3.0+. Let me know if you have more information, but for now I'm gonna close this
