### ISSUE TITLE
Nobody can join the server

### ISSUE THREAD

**Issue by DaviceXD** [Andavin/Images#45]
In my 1.19 server, nobody can join the server if this plugin is active. The error says: "Invalid move player packet received"

**Comment by bitdomo** [comment]
can confrim 1.19 paperspigot
getting "Invalid move player packet received"
only people who are connecting through floodgate+geyser with bedrock edition can join the server

**Comment by CloudeLecaw** [comment]
We also use paper 1.19 and all Vanilla Clients can join there.  So i dont think its a cmi thing...

**Comment by DaviceXD** [comment]
Ok so I tried with a brand new paperspigot server and everything works if there is no plugin other than Images

**Comment by DaviceXD** [comment]
I did a more testing, it seems that the error occurs when online-mode is set to false in the file server.properties and the latest version of SkinsRestorerX-DEV is begin used (downloaded from https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorerX-DEV/)

**Comment by Andavin** [comment]
Fixed in the current version 2.2.7. Thanks for the info!
