### ISSUE TITLE
Invalid move player packet received

### ISSUE THREAD

**Issue by shadryck** [Andavin/Images#48]
Upon joining server papermc errors "Invalid move player packet received".

I'm getting this reproducable issue on latest paper-1.19-58 & java 17.0.3.1, with only images-2.2.6 and Denizen-1.2.5-b1772-REL enabled when 2 clients try to connect to server and rejoin a second time.

Considering the sudden influx of issues about the same "Invalid move player packet received" error and multiple people are reporting it to be a compatibility issue with various different plugins, such as Denizen, Geyser, ViaVersion, SkinsRestorerX chances are high that the issue lies not with all other plugins.

#47 #46 #45

**Comment by shadryck** [comment]
Update: after deleting the playerdata files in \world\playerdata the player can always join the first time, but errors again after rejoin.

**Comment by agoniaprivat** [comment]
I can reproduce this, with only the "Images" plugin.

**Comment by Andavin** [comment]
Finally fixed with the current version
