### ISSUE TITLE
Player can't use the sword normally

### ISSUE THREAD

**Issue by klxf** [Andavin/Images#49]
With the Images plugin installed, the player's swords have reduced attack power, and can't Sweep Attacks.

- My ProtocolLib version: ProtocolLib v5.0.0-SNAPSHOT
- My server version: git-Purpur-1758 (MC: 1.19.2)
- My Java version: 17.0.1

English is not my native language, please excuse typing errors.

**Comment by Andavin** [comment]
I don't see a way that the image plugin could affect this in any way. Did you test by removing and adding back the plugin and it displayed this behavior?

**Comment by klxf** [comment]
> I don't see a way that the image plugin could affect this in any way. Did you test by removing and adding back the plugin and it displayed this behavior?

Sorry to bother, I just found out that this is a bug in ProtocolLib. The new version of ProtocolLib has fixed this bug.
