### ISSUE TITLE
Images plugin suddenly not working 

### ISSUE THREAD

**Issue by thames50** [Andavin/Images#5]
Hello, for some reason Images has stopped working on my server. This is what is displayed when custom images is being loaded.  https://pastebin.com/4vihY9rC
I have tried reinstalling the plugin and deleting the plugin folder but the plugin is still disabled. 

Also, my console displays this error. could this be linked to why Images isn't working 

[Server] WARN Failed to initialize SQLite profile cache. Cache is memory-only.

Another plugin that stopped working as well is PlotSquared.

Paper version 1.14.4
Images version 2.0.5
I have protocollib installed

Thanks

**Comment by Andavin** [comment]
This is something to do with the SQLite driver included in Paper. If you haven't updated Paper in a while try re-downloading it. Otherwise, I'm honestly not sure what to do since this isn't an included dependency in Custom Images.
