### ISSUE TITLE
Sweeping Edge stopped working

### ISSUE THREAD

**Issue by Bloodlex** [Andavin/Images#52]
Hi,

I have no idea how it is related, but Sweeping Edge doesn't work after enabling Custom Images. I know it's odd, because it seems not to be related at all, however that's what we've noticed on our server.

Could you please share if this may have any impact on it? 🙂.

Thanks a lot for your help.

Server Version: git-Purpur-1749 (MC: 1.19.1)*
Custom images version: 2.2.6 (because I guess I shouldn't use the newest one not on 1.19.2).

Other plugins: ActionHealth, AdvancedChests, AdvancedRegionMarket, ajParkour, AntiWorldFly, AsyncWorldEdit, AureliumSkills, AuthMe, Bank, BetterHeads, ChatEmojis, ChestSort, Cigarette, CMI, CMILib, CommandNotifier, CommandPanels, ContainerPassthrough, Core, CraftBook, DeathPenalties, DiscordSRV, dynmap, Dynmap-WorldGuard*, EasyCarts, Epidemic, EvenMoreFish, ExcellentEnchants, GSit, Harbor, HolographicDisplays, InteractionVisualizer, ItemFrameToggle, Jobs, KauriVPN, KelpEffect, LangUtils, LevelledMobs, LimitPillagers, LogBlock, LuckPerms, LWC, LWCTrust, MarriageMaster, Minepacks, MobArena, MyCommand, NBTAPI, NexEngine, NoElytra*, Pingas*, PL-Hide-Pro, PlaceholderAPI, Plan, PortalFix*, ProtocolLib, PvPManager, QSFindItemAddOn, QuickShop, QuickShopList, RedstoneDetector*, RegionRaid, SelectionVisualizer, ShulkerPacks, SkinsRestorer, spark, Spartan, StackMob, StarMail, SuperVanish, TAB, TradingCards, Unstripper, Vault, Vegas, Vehicles, VehiclesFlags, VentureChat, WorldEdit, WorldGuard, WorldGuardExtraFlags

Best regards,
Bloodlex

**Comment by CloudeLecaw** [comment]
use2.2.7

**Comment by Bloodlex** [comment]
> use2.2.7 it doesnt matter if your not using 1.19.2

Unfortunately, using the newest version doesn't solve the problem 🙁 .

**Comment by GitNuck** [comment]
I encountered this when I updated as well, enchants and attack damage on melee weapons are negated by Images.  Bows are unaffected however.  No errors in console at all.  1.19.2 Purpur.
![SF Info](https://user-images.githubusercontent.com/88690764/185780873-a6cf7172-4a12-4618-9b2b-fa452d7a3537.png)
![Plugins2](https://user-images.githubusercontent.com/88690764/185780875-8f6635a0-923f-42a2-b9a2-3f725337a7dd.png)

**Comment by CloudeLecaw** [comment]
well normlay images does not affect any enchants. have you tried  a clean testserver just with images on it and some Enchant items?

**Comment by resi23** [comment]
> well normlay images does not affect any enchants. have you tried a clean testserver just with images on it and some Enchant items?

Have you Protocollib installed delete it an try again

**Comment by CloudeLecaw** [comment]
Closed because it seem to be solved with no responce from TO fro arround 2 years
