### ISSUE TITLE
Problem image

### ISSUE THREAD

**Issue by BrayaanPS** [Andavin/Images#6]
Hello, I currently have this problem with the images of my server https://i.imgur.com/e8K9Nf4.png (previous server images are displayed).

- Use: bungeecord.
- Plugin version: 2.0.5
- Database: sqlite
- Jar: Paper 1.8.8
- Procotollib: yes

**Comment by Sergix7720** [comment]
Hey, I'm having the same problem, images from all my servers in my bungee get all mixed up in the 1.8 client.
Did you find any fix?

**Comment by BrayaanPS** [comment]
> Hey, I'm having the same problem, images from all my servers in my bungee get all mixed up in the 1.8 client.
> Did you find any fix?

I have no idea, now I'm using my server without a bungee cord and it's working fine.

**Comment by Andavin** [comment]
Hmm... these seems to be a reoccurring issue with BungeeCord. I don't understand how, when using SQLite, an image could possibly be loaded on a different server. The databases are in physically different files.

Regardless, my plans are to rewrite the entire data storage system at some point and add a dedicated BungeeCord plugin which would solve this. For now, all I can recommend is make sure you're using SQLite and that the servers are in separate folders from one another (I don't know how they wouldn't be).
