### ISSUE TITLE
Please 1.20.1 update  --<-@

### ISSUE THREAD

**Issue by Blueeyestar** [Andavin/Images#70]
Hello, it would be really nice if there would be a 1.20.1 for the plugin soon. Then we could update.
Thank you in advance and keep up the good work

**Comment by games4681** [comment]
You can download here a unoffical plugin update until the dev release offical update https://github.com/resi23/Images

**Comment by Blueeyestar** [comment]
> You can download here a unoffical plugin update until the dev release offical update https://github.com/resi23/Images

Only if you don't know how to work with Maven or Eclipse... unfortunately the unofficial update doesn't help much either.

**Comment by resi23** [comment]
no, there is a jar under releases

**Comment by Blueeyestar** [comment]
> no, there is a jar under releases https://github.com/resi23/Images/releases

That's really great. that even works. Many thanks for your hint and help

**Comment by CloudeLecaw** [comment]
well i think the Ticket can be closed, as the update is on spigot allready :-)
