### ISSUE TITLE
Please update the plugin to support 1.20.2

### ISSUE THREAD

**Issue by zfsbsdf** [Andavin/Images#75]
When you put the plug-in into the plug-in folder of the 1.20.2 paper and run it, an error will appear.
![1](https://github.com/Andavin/Images/assets/113145735/d8e1c992-e3e4-4c07-828c-8c0b9c461810)

**Comment by CloudeLecaw** [comment]
we also use 1.20.2 and the plugin was working fine...

**Comment by zfsbsdf** [comment]
very thankful

**Comment by CloudeLecaw** [comment]
this ticket can be closed
