### ISSUE TITLE
Cannot resolve org.spigotmc:spigot:1.20.2-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by christmas3294** [Andavin/Images#81]
<dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.20.2-R0.1-SNAPSHOT</version>
            <classifier>remapped-mojang</classifier>
            <scope>provided</scope>
        </dependency>
not used  <classifier>remapped-mojang</classifier> 
how do this problem?

**Comment by CloudeLecaw** [comment]
1.20.2 is ni good Version to use at least. uye 1.20.1 or 1.20.4
the devs did not made updates for these small fishes called 1.20.2 and 1.20.3 because they where replaced quickly with 1.20.4  so tell your plugin devs not to develop for 1.20.2 anymore
