### ISSUE TITLE
Please Update for Version 1.20.5/6 - 1_20_R4

### ISSUE THREAD

**Issue by CloudeLecaw** [Andavin/Images#83]
Version 1.20.5 and 1.20.6 both use the same 1_20_R4

So it would be nice to have an update

**Comment by DICEALPHAHU** [comment]
plz update

**Comment by resi23** [comment]
I created this build temporarily: https://github.com/resi23/Images/releases/tag/v2.3.3 its Supports Paper Server

This is not an official build. Keep an eye on the [Spigot page](https://www.spigotmc.org/resources/custom-images.53036/) for an official update.

**Comment by DICEALPHAHU** [comment]
> I created this build temporarily: https://github.com/resi23/Images/releases/tag/v2.3.3 its Supports 1.20.5/6 Spigot and Paper Server
> 
> This is not an official build. Keep an eye on the [Spigot page](https://www.spigotmc.org/resources/custom-images.53036/) for an official update.


give 1000 ♥ to u and many thanks

**Comment by DICEALPHAHU** [comment]
> I created this build temporarily: https://github.com/resi23/Images/releases/tag/v2.3.3 its Supports 1.20.5/6 Spigot and Paper Server
> 
> This is not an official build. Keep an eye on the [Spigot page](https://www.spigotmc.org/resources/custom-images.53036/) for an official update.

u can request a Pull to author and it will be work fine

**Comment by CloudeLecaw** [comment]
i did that is why i got the 2.4 from the devs post on spigot where he added the version 2.4.0

![Screenshot_2024-05-31-12-34-20-634_com android chrome-edit](https://github.com/Andavin/Images/assets/12080017/9f60242f-6609-43ef-b86f-2432db0b8614)

**Comment by CloudeLecaw** [comment]
solved with version 2.3.3
