### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by veeonthewall** [Andavin/Images#88]
Plugin does not work on 1.20.6.

**Comment by CloudeLecaw** [comment]
support for 1.20.6 was added with version 2.3.3
its just not released on spigot yet.

https://github.com/resi23/Images/releases/tag/v2.3.3

**Comment by resi23** [comment]
I don't think you should close the issue. People rarely look at closed issues and so there will always be new 1.20.5/6 issues. Also, my temporary version is not the official one so keep an eye on the Spigot page and this repo.

**Comment by CloudeLecaw** [comment]
reopend for others that look for a Version that works on 1.20.5/6

**Comment by resi23** [comment]
work on Spigot 1.20.5/6 and 1.21
https://github.com/resi23/Images/releases/tag/v2.3.4

**Comment by resi23** [comment]
Version 2.3.4-PaperFix works now with 1.21 Spigot AND Paper
https://github.com/resi23/Images/releases/tag/v2.3.4-PaperFix

**Comment by CloudeLecaw** [comment]
closed because it was updated
